package testing;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.datatransfer.StringSelection;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import javax.swing.text.html.parser.DTDConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ady
 */
public class prin extends javax.swing.JFrame {
    public static int plecare;
    public static int sosire;
    public static int nr_sofer;
    public static int plata;
    public static int pret;
    public static String at;
    public static int avans;
    public static double pMot;
    public void calcul(){
        plata=(sosire-plecare)*pret/100;
    }
    /**
     * Creates new form prin
     */
    public prin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abtfr = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        nr_soferi = new javax.swing.ButtonGroup();
        alta_tara = new javax.swing.JDialog();
        alta_tara_txt = new javax.swing.JTextField();
        ok_alta_tara = new javax.swing.JButton();
        cancel_alta_tara = new javax.swing.JButton();
        hlpfr = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        hlpTxtArea = new javax.swing.JTextArea();
        OpenFileFrame = new javax.swing.JFrame();
        OpenFile = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        pretkm = new javax.swing.JTextArea();
        unsofer = new javax.swing.JRadioButton();
        doisoferi = new javax.swing.JRadioButton();
        numars = new javax.swing.JTextField();
        kmplecare = new javax.swing.JTextField();
        ikmplecare = new javax.swing.JTextField();
        kmsosire = new javax.swing.JTextField();
        ikmsosire = new javax.swing.JTextField();
        kmparcursi = new javax.swing.JTextField();
        ikmparcursi = new javax.swing.JTextField();
        ipretkm = new javax.swing.JTextField();
        alimentari = new javax.swing.JTextField();
        pretpelitru = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        DefaultListModel model=new DefaultListModel();
        model.addElement("Romania");
        model.addElement("Ungaria");
        model.addElement("Slovenia");
        model.addElement("Italia");
        model.addElement("Bulgaria");
        model.addElement("Grecia");
        Tari = new javax.swing.JList();
        rList = new javax.swing.JButton();
        aList = new javax.swing.JButton();
        pretTxtField = new javax.swing.JTextField();
        avansCursa = new javax.swing.JTextField();
        iAvansCursa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        Cut = new javax.swing.JMenuItem();
        Copy = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        hlp = new javax.swing.JMenuItem();
        abt = new javax.swing.JMenuItem();

        abtfr.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        abtfr.setTitle("About");
        abtfr.setAlwaysOnTop(true);
        abtfr.setAutoRequestFocus(false);
        abtfr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        abtfr.setFocusCycleRoot(false);
        abtfr.setLocationByPlatform(true);
        abtfr.setMinimumSize(new java.awt.Dimension(300, 150));
        abtfr.setPreferredSize(new java.awt.Dimension(300, 300));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Program pt calcularea decontului");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout abtfrLayout = new javax.swing.GroupLayout(abtfr.getContentPane());
        abtfr.getContentPane().setLayout(abtfrLayout);
        abtfrLayout.setHorizontalGroup(
            abtfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abtfrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        abtfrLayout.setVerticalGroup(
            abtfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abtfrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abtfr.getAccessibleContext().setAccessibleDescription("");

        nr_soferi.add(unsofer);
        nr_soferi.add(doisoferi);

        alta_tara.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        alta_tara.setTitle("Alta tara...");
        alta_tara.setAlwaysOnTop(true);
        alta_tara.setMinimumSize(new java.awt.Dimension(300, 300));

        ok_alta_tara.setText("OK");
        ok_alta_tara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_alta_taraActionPerformed(evt);
            }
        });

        cancel_alta_tara.setText("Cancel");
        cancel_alta_tara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_alta_taraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alta_taraLayout = new javax.swing.GroupLayout(alta_tara.getContentPane());
        alta_tara.getContentPane().setLayout(alta_taraLayout);
        alta_taraLayout.setHorizontalGroup(
            alta_taraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alta_taraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alta_taraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alta_tara_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alta_taraLayout.createSequentialGroup()
                        .addComponent(ok_alta_tara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel_alta_tara)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        alta_taraLayout.setVerticalGroup(
            alta_taraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alta_taraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(alta_tara_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(alta_taraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_alta_tara)
                    .addComponent(cancel_alta_tara))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        hlpfr.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        hlpfr.setMinimumSize(new java.awt.Dimension(500, 200));

        hlpTxtArea.setEditable(false);
        hlpTxtArea.setColumns(20);
        hlpTxtArea.setRows(5);
        hlpTxtArea.setText("Pt ajutor si alte probleme contact Nicorici Adrian.\nTel: 0728161926\nE-mail: nicorici.adrian@yahoo.com\t\n              ady.niko51@gmail.com\nSkype: adrian.nicorici");
        jScrollPane4.setViewportView(hlpTxtArea);

        javax.swing.GroupLayout hlpfrLayout = new javax.swing.GroupLayout(hlpfr.getContentPane());
        hlpfr.getContentPane().setLayout(hlpfrLayout);
        hlpfrLayout.setHorizontalGroup(
            hlpfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hlpfrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        hlpfrLayout.setVerticalGroup(
            hlpfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hlpfrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        OpenFileFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        OpenFileFrame.setMinimumSize(new java.awt.Dimension(582, 397));

        OpenFile.setApproveButtonText("");
        OpenFile.setApproveButtonToolTipText("");
        //FileFilter filter=new FileNameExtensionFilter("text","txt","doc");
        //OpenFile.addChoosableFileFilter(filter);
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpenFileFrameLayout = new javax.swing.GroupLayout(OpenFileFrame.getContentPane());
        OpenFileFrame.getContentPane().setLayout(OpenFileFrameLayout);
        OpenFileFrameLayout.setHorizontalGroup(
            OpenFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenFileFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OpenFileFrameLayout.setVerticalGroup(
            OpenFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenFileFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decont");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pretkm.setEditable(false);
        pretkm.setColumns(20);
        pretkm.setRows(5);
        pretkm.setText("Pret/100km");
        pretkm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(pretkm);

        unsofer.setText("1");
        unsofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unsoferActionPerformed(evt);
            }
        });

        doisoferi.setText("2");
        doisoferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisoferiActionPerformed(evt);
            }
        });

        numars.setEditable(false);
        numars.setText("Nr. soferi:");
        numars.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        numars.setSelectedTextColor(new java.awt.Color(240, 240, 240));

        kmplecare.setEditable(false);
        kmplecare.setText("Km. plecare");
        kmplecare.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kmplecare.setPreferredSize(new java.awt.Dimension(55, 20));

        ikmplecare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikmplecareActionPerformed(evt);
            }
        });

        kmsosire.setEditable(false);
        kmsosire.setText("Km. sosire");
        kmsosire.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ikmsosire.setMinimumSize(new java.awt.Dimension(86, 20));
        ikmsosire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikmsosireActionPerformed(evt);
            }
        });

        kmparcursi.setEditable(false);
        kmparcursi.setText("Km. parcursi");
        kmparcursi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kmparcursi.setPreferredSize(new java.awt.Dimension(55, 20));
        kmparcursi.setSelectionEnd(10);
        kmparcursi.setSelectionStart(10);
        kmparcursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmparcursiActionPerformed(evt);
            }
        });

        ikmparcursi.setEditable(false);
        ikmparcursi.setMinimumSize(new java.awt.Dimension(86, 20));
        ikmparcursi.setPreferredSize(new java.awt.Dimension(86, 20));
        ikmparcursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikmparcursiActionPerformed(evt);
            }
        });

        ipretkm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ipretkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipretkmActionPerformed(evt);
            }
        });

        alimentari.setEditable(false);
        alimentari.setText("Alimentat");

        pretpelitru.setEditable(false);
        pretpelitru.setText("Pret/l (orice moneda)");

        Tari.setModel(model);
        Tari.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        Tari.setValueIsAdjusting(true);
        Tari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TariMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tari);

        rList.setText("Sterge din lista");
        rList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rListActionPerformed(evt);
            }
        });

        aList.setText("Adauga");
        aList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aListActionPerformed(evt);
            }
        });

        pretTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretTxtFieldActionPerformed(evt);
            }
        });

        avansCursa.setEditable(false);
        avansCursa.setText("Avans cursa:");

        iAvansCursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAvansCursaActionPerformed(evt);
            }
        });

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        File.add(Save);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        Edit.setText("Edit");

        Undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        Undo.setText("Undo");
        Edit.add(Undo);

        Redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Redo.setText("Redo");
        Edit.add(Redo);

        Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        Cut.setText("Cut");
        Edit.add(Cut);

        Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Copy.setText("Copy");
        Edit.add(Copy);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Paste");
        Edit.add(jMenuItem1);

        jMenuBar1.add(Edit);

        help.setText("Help");

        hlp.setText("Help");
        hlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlpActionPerformed(evt);
            }
        });
        help.add(hlp);

        abt.setText("About");
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });
        help.add(abt);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(numars, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unsofer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doisoferi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(avansCursa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ipretkm, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(iAvansCursa)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alimentari, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pretpelitru, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(pretTxtField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(746, 746, 746)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kmparcursi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ikmparcursi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kmsosire, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ikmsosire, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kmplecare, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ikmplecare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unsofer)
                    .addComponent(doisoferi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ipretkm, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avansCursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iAvansCursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alimentari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pretpelitru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aList)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(pretTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(rList)))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikmplecare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmplecare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikmsosire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmsosire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ikmparcursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmparcursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
        // TODO add your handling code here:
        abtfr.setVisible(true);
    }//GEN-LAST:event_abtActionPerformed

    private void unsoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsoferActionPerformed
        // TODO add your handling code here:
        String txt;
        txt=unsofer.getText();
        nr_sofer=Integer.parseInt(txt);
        
        
    }//GEN-LAST:event_unsoferActionPerformed

    private void doisoferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisoferiActionPerformed
        // TODO add your handling code here:
        String txt;
        txt=doisoferi.getText();
        nr_sofer=Integer.parseInt(txt);
        
    }//GEN-LAST:event_doisoferiActionPerformed

    private void ikmplecareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikmplecareActionPerformed
        // TODO add your handling code here:
        String text1;
        text1=ikmplecare.getText();
        plecare=Integer.parseInt(text1);
    }//GEN-LAST:event_ikmplecareActionPerformed

    private void ikmsosireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikmsosireActionPerformed
        // TODO add your handling code here:
        String text2;
        text2=ikmsosire.getText();
        sosire=Integer.parseInt(text2);
    }//GEN-LAST:event_ikmsosireActionPerformed

    private void ikmparcursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikmparcursiActionPerformed
        // TODO add your handling code here:
        int total;
        String text3;
        total=sosire-plecare;
        text3=Integer.toString(total);
        ikmparcursi.setText(text3);
    }//GEN-LAST:event_ikmparcursiActionPerformed

    private void kmparcursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmparcursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmparcursiActionPerformed

    private void ipretkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipretkmActionPerformed
        // TODO add your handling code here:
        String txt;
        txt=ipretkm.getText();
        pret=Integer.parseInt(txt);
    }//GEN-LAST:event_ipretkmActionPerformed

    private void ok_alta_taraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_alta_taraActionPerformed
        // TODO add your handling code here:
        int size;
        size=Tari.getModel().getSize();
        at=alta_tara_txt.getText();
        DefaultListModel mdl=(DefaultListModel) Tari.getModel();
        int sz= Tari.getModel().getSize();
        mdl.add(size, at);
        Tari.setModel(mdl);
        alta_tara_txt.setText(null);
        alta_tara.dispose();
    }//GEN-LAST:event_ok_alta_taraActionPerformed

    private void cancel_alta_taraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_alta_taraActionPerformed
        // TODO add your handling code here:
        alta_tara.dispose();
    }//GEN-LAST:event_cancel_alta_taraActionPerformed

    private void TariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TariMouseClicked

    private void rListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rListActionPerformed
        // TODO add your handling code here:
        DefaultListModel md2=(DefaultListModel) Tari.getModel();
        md2.remove(Tari.getSelectedIndex());
        Tari.setModel(md2);
    }//GEN-LAST:event_rListActionPerformed

    private void aListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aListActionPerformed
        // TODO add your handling code here:
        alta_tara.setVisible(true);
    }//GEN-LAST:event_aListActionPerformed

    private void iAvansCursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAvansCursaActionPerformed
        // TODO add your handling code here:
        String text;
        text=iAvansCursa.getText();
        avans=Integer.parseInt(text);
    }//GEN-LAST:event_iAvansCursaActionPerformed

    private void hlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlpActionPerformed
        // TODO add your handling code here:
        hlpfr.setVisible(true);
        hlpfr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_hlpActionPerformed

    private void pretTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretTxtFieldActionPerformed
        // TODO add your handling code here:
        String text;
        text=pretTxtField.getText();
        pMot=Double.parseDouble(text);
    }//GEN-LAST:event_pretTxtFieldActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        OpenFileFrame.setVisible(true);
    }//GEN-LAST:event_OpenActionPerformed

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new prin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem Open;
    private javax.swing.JFileChooser OpenFile;
    private javax.swing.JFrame OpenFileFrame;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Save;
    private javax.swing.JList Tari;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JButton aList;
    private javax.swing.JMenuItem abt;
    private javax.swing.JFrame abtfr;
    private javax.swing.JTextField alimentari;
    private javax.swing.JDialog alta_tara;
    private javax.swing.JTextField alta_tara_txt;
    private javax.swing.JTextField avansCursa;
    private javax.swing.JButton cancel_alta_tara;
    private javax.swing.JRadioButton doisoferi;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem hlp;
    private javax.swing.JTextArea hlpTxtArea;
    private javax.swing.JFrame hlpfr;
    private javax.swing.JTextField iAvansCursa;
    private javax.swing.JTextField ikmparcursi;
    private javax.swing.JTextField ikmplecare;
    private javax.swing.JTextField ikmsosire;
    private javax.swing.JTextField ipretkm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField kmparcursi;
    private javax.swing.JTextField kmplecare;
    private javax.swing.JTextField kmsosire;
    private javax.swing.ButtonGroup nr_soferi;
    private javax.swing.JTextField numars;
    private javax.swing.JButton ok_alta_tara;
    private javax.swing.JTextField pretTxtField;
    private javax.swing.JTextArea pretkm;
    private javax.swing.JTextField pretpelitru;
    private javax.swing.JButton rList;
    private javax.swing.JRadioButton unsofer;
    // End of variables declaration//GEN-END:variables
}
